### ISSUE TITLE
BUG | Elements at wrong locations

### ISSUE THREAD

**Issue by SmartGecko44** [SmartGecko44/SmartGecko44.github.io#4]
**Describe the bug**
The dark mode button and cookie dialogue move to the top of the page when the dark mode dialogue is open.

**To Reproduce**
1. Open the page
2. Click the dark mode button
3. The bug happens

**Expected behavior**
The button and dialogue stay at the expected location

**Screenshots**

**Client (please complete the following information, if applicable):**
 - Chrome

**Additionnel informations**
The bug doesn't happen in Safari.

**Comment by SmartGecko44** [comment]
Skill issue for Chrome users but I will look into it.

**Comment by SmartGecko44** [comment]
I have narrowed the issue down to 
```css
body.inBackground {
    filter: blur(5px);
    transition: all 1s ease-in-out;
}
``` 
inside of backgrounds.css
